# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pm4YxeOXatS1LGwD-e7MMw1dlO2HlQpQ
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as num
url='/content/Train-Set.csv'
df=pd.read_csv(url)
print(df)
mean_value=df['OutletSales'].mean()
print(f"mean value:-{mean_value}")
mode_value=df['OutletSales'].mode()
print(f"mode value:-{mode_value}")
median_value=df['OutletSales'].median()
print(f"median value:-{median_value}")
std_value=df['OutletSales'].std()
print(f"standard deviation  value:-{std_value}")
var_value=df['OutletSales'].var()
print(f"variance value:-{var_value}")
skew_value=df['OutletSales'].skew()
print(f"skewness value:-{skew_value}")
kur_value=df['OutletSales'].kurt()
print(f"kurtosis value:-{kur_value}")
df['OutletSales'].value_counts().plot(kind='bar', title='OutletSales Count')
plt.xlabel('OutletSales')
plt.ylabel('Count')
plt.show()